// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/protos/event_store.proto

package nandestech.protos;

public final class EventStoreOuterClass {
  private EventStoreOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventStoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:nandestech.protos.EventStore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string event_store_id = 1;</code>
     * @return The eventStoreId.
     */
    java.lang.String getEventStoreId();
    /**
     * <code>string event_store_id = 1;</code>
     * @return The bytes for eventStoreId.
     */
    com.google.protobuf.ByteString
        getEventStoreIdBytes();

    /**
     * <code>string event_name = 2;</code>
     * @return The eventName.
     */
    java.lang.String getEventName();
    /**
     * <code>string event_name = 2;</code>
     * @return The bytes for eventName.
     */
    com.google.protobuf.ByteString
        getEventNameBytes();

    /**
     * <code>string item_number = 3;</code>
     * @return The itemNumber.
     */
    java.lang.String getItemNumber();
    /**
     * <code>string item_number = 3;</code>
     * @return The bytes for itemNumber.
     */
    com.google.protobuf.ByteString
        getItemNumberBytes();

    /**
     * <code>string item_type = 4;</code>
     * @return The itemType.
     */
    java.lang.String getItemType();
    /**
     * <code>string item_type = 4;</code>
     * @return The bytes for itemType.
     */
    com.google.protobuf.ByteString
        getItemTypeBytes();

    /**
     * <code>int32 user_id = 5;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>string user_login = 6;</code>
     * @return The userLogin.
     */
    java.lang.String getUserLogin();
    /**
     * <code>string user_login = 6;</code>
     * @return The bytes for userLogin.
     */
    com.google.protobuf.ByteString
        getUserLoginBytes();

    /**
     * <code>int32 node_id = 7;</code>
     * @return The nodeId.
     */
    int getNodeId();

    /**
     * <code>string node_code = 8;</code>
     * @return The nodeCode.
     */
    java.lang.String getNodeCode();
    /**
     * <code>string node_code = 8;</code>
     * @return The bytes for nodeCode.
     */
    com.google.protobuf.ByteString
        getNodeCodeBytes();

    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();
  }
  /**
   * Protobuf type {@code nandestech.protos.EventStore}
   */
  public static final class EventStore extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:nandestech.protos.EventStore)
      EventStoreOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventStore.newBuilder() to construct.
    private EventStore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventStore() {
      eventStoreId_ = "";
      eventName_ = "";
      itemNumber_ = "";
      itemType_ = "";
      userLogin_ = "";
      nodeCode_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventStore();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return nandestech.protos.EventStoreOuterClass.internal_static_nandestech_protos_EventStore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return nandestech.protos.EventStoreOuterClass.internal_static_nandestech_protos_EventStore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              nandestech.protos.EventStoreOuterClass.EventStore.class, nandestech.protos.EventStoreOuterClass.EventStore.Builder.class);
    }

    public static final int EVENT_STORE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eventStoreId_ = "";
    /**
     * <code>string event_store_id = 1;</code>
     * @return The eventStoreId.
     */
    @java.lang.Override
    public java.lang.String getEventStoreId() {
      java.lang.Object ref = eventStoreId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventStoreId_ = s;
        return s;
      }
    }
    /**
     * <code>string event_store_id = 1;</code>
     * @return The bytes for eventStoreId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventStoreIdBytes() {
      java.lang.Object ref = eventStoreId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventStoreId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object eventName_ = "";
    /**
     * <code>string event_name = 2;</code>
     * @return The eventName.
     */
    @java.lang.Override
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      }
    }
    /**
     * <code>string event_name = 2;</code>
     * @return The bytes for eventName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEM_NUMBER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object itemNumber_ = "";
    /**
     * <code>string item_number = 3;</code>
     * @return The itemNumber.
     */
    @java.lang.Override
    public java.lang.String getItemNumber() {
      java.lang.Object ref = itemNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemNumber_ = s;
        return s;
      }
    }
    /**
     * <code>string item_number = 3;</code>
     * @return The bytes for itemNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemNumberBytes() {
      java.lang.Object ref = itemNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEM_TYPE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object itemType_ = "";
    /**
     * <code>string item_type = 4;</code>
     * @return The itemType.
     */
    @java.lang.Override
    public java.lang.String getItemType() {
      java.lang.Object ref = itemType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        itemType_ = s;
        return s;
      }
    }
    /**
     * <code>string item_type = 4;</code>
     * @return The bytes for itemType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemTypeBytes() {
      java.lang.Object ref = itemType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 5;
    private int userId_ = 0;
    /**
     * <code>int32 user_id = 5;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int USER_LOGIN_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userLogin_ = "";
    /**
     * <code>string user_login = 6;</code>
     * @return The userLogin.
     */
    @java.lang.Override
    public java.lang.String getUserLogin() {
      java.lang.Object ref = userLogin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userLogin_ = s;
        return s;
      }
    }
    /**
     * <code>string user_login = 6;</code>
     * @return The bytes for userLogin.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserLoginBytes() {
      java.lang.Object ref = userLogin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userLogin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_ID_FIELD_NUMBER = 7;
    private int nodeId_ = 0;
    /**
     * <code>int32 node_id = 7;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public int getNodeId() {
      return nodeId_;
    }

    public static final int NODE_CODE_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nodeCode_ = "";
    /**
     * <code>string node_code = 8;</code>
     * @return The nodeCode.
     */
    @java.lang.Override
    public java.lang.String getNodeCode() {
      java.lang.Object ref = nodeCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeCode_ = s;
        return s;
      }
    }
    /**
     * <code>string node_code = 8;</code>
     * @return The bytes for nodeCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeCodeBytes() {
      java.lang.Object ref = nodeCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_AT_FIELD_NUMBER = 9;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return Whether the createdAt field is set.
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 9;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventStoreId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventStoreId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemNumber_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, itemNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, itemType_);
      }
      if (userId_ != 0) {
        output.writeInt32(5, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userLogin_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userLogin_);
      }
      if (nodeId_ != 0) {
        output.writeInt32(7, nodeId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, nodeCode_);
      }
      if (createdAt_ != null) {
        output.writeMessage(9, getCreatedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventStoreId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventStoreId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemNumber_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, itemNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itemType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, itemType_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userLogin_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userLogin_);
      }
      if (nodeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, nodeId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nodeCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, nodeCode_);
      }
      if (createdAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getCreatedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof nandestech.protos.EventStoreOuterClass.EventStore)) {
        return super.equals(obj);
      }
      nandestech.protos.EventStoreOuterClass.EventStore other = (nandestech.protos.EventStoreOuterClass.EventStore) obj;

      if (!getEventStoreId()
          .equals(other.getEventStoreId())) return false;
      if (!getEventName()
          .equals(other.getEventName())) return false;
      if (!getItemNumber()
          .equals(other.getItemNumber())) return false;
      if (!getItemType()
          .equals(other.getItemType())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getUserLogin()
          .equals(other.getUserLogin())) return false;
      if (getNodeId()
          != other.getNodeId()) return false;
      if (!getNodeCode()
          .equals(other.getNodeCode())) return false;
      if (hasCreatedAt() != other.hasCreatedAt()) return false;
      if (hasCreatedAt()) {
        if (!getCreatedAt()
            .equals(other.getCreatedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_STORE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEventStoreId().hashCode();
      hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEventName().hashCode();
      hash = (37 * hash) + ITEM_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getItemNumber().hashCode();
      hash = (37 * hash) + ITEM_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getItemType().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + USER_LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getUserLogin().hashCode();
      hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNodeId();
      hash = (37 * hash) + NODE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeCode().hashCode();
      if (hasCreatedAt()) {
        hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static nandestech.protos.EventStoreOuterClass.EventStore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(nandestech.protos.EventStoreOuterClass.EventStore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code nandestech.protos.EventStore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:nandestech.protos.EventStore)
        nandestech.protos.EventStoreOuterClass.EventStoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return nandestech.protos.EventStoreOuterClass.internal_static_nandestech_protos_EventStore_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return nandestech.protos.EventStoreOuterClass.internal_static_nandestech_protos_EventStore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                nandestech.protos.EventStoreOuterClass.EventStore.class, nandestech.protos.EventStoreOuterClass.EventStore.Builder.class);
      }

      // Construct using nandestech.protos.EventStoreOuterClass.EventStore.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        eventStoreId_ = "";
        eventName_ = "";
        itemNumber_ = "";
        itemType_ = "";
        userId_ = 0;
        userLogin_ = "";
        nodeId_ = 0;
        nodeCode_ = "";
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return nandestech.protos.EventStoreOuterClass.internal_static_nandestech_protos_EventStore_descriptor;
      }

      @java.lang.Override
      public nandestech.protos.EventStoreOuterClass.EventStore getDefaultInstanceForType() {
        return nandestech.protos.EventStoreOuterClass.EventStore.getDefaultInstance();
      }

      @java.lang.Override
      public nandestech.protos.EventStoreOuterClass.EventStore build() {
        nandestech.protos.EventStoreOuterClass.EventStore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nandestech.protos.EventStoreOuterClass.EventStore buildPartial() {
        nandestech.protos.EventStoreOuterClass.EventStore result = new nandestech.protos.EventStoreOuterClass.EventStore(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(nandestech.protos.EventStoreOuterClass.EventStore result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.eventStoreId_ = eventStoreId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.eventName_ = eventName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.itemNumber_ = itemNumber_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.itemType_ = itemType_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.userLogin_ = userLogin_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.nodeId_ = nodeId_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.nodeCode_ = nodeCode_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.createdAt_ = createdAtBuilder_ == null
              ? createdAt_
              : createdAtBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nandestech.protos.EventStoreOuterClass.EventStore) {
          return mergeFrom((nandestech.protos.EventStoreOuterClass.EventStore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nandestech.protos.EventStoreOuterClass.EventStore other) {
        if (other == nandestech.protos.EventStoreOuterClass.EventStore.getDefaultInstance()) return this;
        if (!other.getEventStoreId().isEmpty()) {
          eventStoreId_ = other.eventStoreId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getEventName().isEmpty()) {
          eventName_ = other.eventName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getItemNumber().isEmpty()) {
          itemNumber_ = other.itemNumber_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getItemType().isEmpty()) {
          itemType_ = other.itemType_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getUserLogin().isEmpty()) {
          userLogin_ = other.userLogin_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getNodeId() != 0) {
          setNodeId(other.getNodeId());
        }
        if (!other.getNodeCode().isEmpty()) {
          nodeCode_ = other.nodeCode_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.hasCreatedAt()) {
          mergeCreatedAt(other.getCreatedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                eventStoreId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                eventName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                itemNumber_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                itemType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                userId_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                userLogin_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                nodeId_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                nodeCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                input.readMessage(
                    getCreatedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object eventStoreId_ = "";
      /**
       * <code>string event_store_id = 1;</code>
       * @return The eventStoreId.
       */
      public java.lang.String getEventStoreId() {
        java.lang.Object ref = eventStoreId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventStoreId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_store_id = 1;</code>
       * @return The bytes for eventStoreId.
       */
      public com.google.protobuf.ByteString
          getEventStoreIdBytes() {
        java.lang.Object ref = eventStoreId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventStoreId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_store_id = 1;</code>
       * @param value The eventStoreId to set.
       * @return This builder for chaining.
       */
      public Builder setEventStoreId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eventStoreId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string event_store_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventStoreId() {
        eventStoreId_ = getDefaultInstance().getEventStoreId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string event_store_id = 1;</code>
       * @param value The bytes for eventStoreId to set.
       * @return This builder for chaining.
       */
      public Builder setEventStoreIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eventStoreId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object eventName_ = "";
      /**
       * <code>string event_name = 2;</code>
       * @return The eventName.
       */
      public java.lang.String getEventName() {
        java.lang.Object ref = eventName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_name = 2;</code>
       * @return The bytes for eventName.
       */
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        java.lang.Object ref = eventName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_name = 2;</code>
       * @param value The eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        eventName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventName() {
        eventName_ = getDefaultInstance().getEventName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 2;</code>
       * @param value The bytes for eventName to set.
       * @return This builder for chaining.
       */
      public Builder setEventNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        eventName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object itemNumber_ = "";
      /**
       * <code>string item_number = 3;</code>
       * @return The itemNumber.
       */
      public java.lang.String getItemNumber() {
        java.lang.Object ref = itemNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemNumber_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string item_number = 3;</code>
       * @return The bytes for itemNumber.
       */
      public com.google.protobuf.ByteString
          getItemNumberBytes() {
        java.lang.Object ref = itemNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string item_number = 3;</code>
       * @param value The itemNumber to set.
       * @return This builder for chaining.
       */
      public Builder setItemNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        itemNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string item_number = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemNumber() {
        itemNumber_ = getDefaultInstance().getItemNumber();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string item_number = 3;</code>
       * @param value The bytes for itemNumber to set.
       * @return This builder for chaining.
       */
      public Builder setItemNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        itemNumber_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object itemType_ = "";
      /**
       * <code>string item_type = 4;</code>
       * @return The itemType.
       */
      public java.lang.String getItemType() {
        java.lang.Object ref = itemType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          itemType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string item_type = 4;</code>
       * @return The bytes for itemType.
       */
      public com.google.protobuf.ByteString
          getItemTypeBytes() {
        java.lang.Object ref = itemType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string item_type = 4;</code>
       * @param value The itemType to set.
       * @return This builder for chaining.
       */
      public Builder setItemType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        itemType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string item_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemType() {
        itemType_ = getDefaultInstance().getItemType();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string item_type = 4;</code>
       * @param value The bytes for itemType to set.
       * @return This builder for chaining.
       */
      public Builder setItemTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        itemType_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>int32 user_id = 5;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 user_id = 5;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 user_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userLogin_ = "";
      /**
       * <code>string user_login = 6;</code>
       * @return The userLogin.
       */
      public java.lang.String getUserLogin() {
        java.lang.Object ref = userLogin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userLogin_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_login = 6;</code>
       * @return The bytes for userLogin.
       */
      public com.google.protobuf.ByteString
          getUserLoginBytes() {
        java.lang.Object ref = userLogin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userLogin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_login = 6;</code>
       * @param value The userLogin to set.
       * @return This builder for chaining.
       */
      public Builder setUserLogin(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userLogin_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string user_login = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserLogin() {
        userLogin_ = getDefaultInstance().getUserLogin();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string user_login = 6;</code>
       * @param value The bytes for userLogin to set.
       * @return This builder for chaining.
       */
      public Builder setUserLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userLogin_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private int nodeId_ ;
      /**
       * <code>int32 node_id = 7;</code>
       * @return The nodeId.
       */
      @java.lang.Override
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>int32 node_id = 7;</code>
       * @param value The nodeId to set.
       * @return This builder for chaining.
       */
      public Builder setNodeId(int value) {
        
        nodeId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 node_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        nodeId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nodeCode_ = "";
      /**
       * <code>string node_code = 8;</code>
       * @return The nodeCode.
       */
      public java.lang.String getNodeCode() {
        java.lang.Object ref = nodeCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string node_code = 8;</code>
       * @return The bytes for nodeCode.
       */
      public com.google.protobuf.ByteString
          getNodeCodeBytes() {
        java.lang.Object ref = nodeCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string node_code = 8;</code>
       * @param value The nodeCode to set.
       * @return This builder for chaining.
       */
      public Builder setNodeCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nodeCode_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>string node_code = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNodeCode() {
        nodeCode_ = getDefaultInstance().getNodeCode();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>string node_code = 8;</code>
       * @param value The bytes for nodeCode to set.
       * @return This builder for chaining.
       */
      public Builder setNodeCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nodeCode_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createdAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       * @return Whether the createdAt field is set.
       */
      public boolean hasCreatedAt() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       * @return The createdAt.
       */
      public com.google.protobuf.Timestamp getCreatedAt() {
        if (createdAtBuilder_ == null) {
          return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        } else {
          return createdAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdAt_ = value;
        } else {
          createdAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdAtBuilder_ == null) {
          createdAt_ = builderForValue.build();
        } else {
          createdAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        if (createdAtBuilder_ == null) {
          if (((bitField0_ & 0x00000100) != 0) &&
            createdAt_ != null &&
            createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCreatedAtBuilder().mergeFrom(value);
          } else {
            createdAt_ = value;
          }
        } else {
          createdAtBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public Builder clearCreatedAt() {
        bitField0_ = (bitField0_ & ~0x00000100);
        createdAt_ = null;
        if (createdAtBuilder_ != null) {
          createdAtBuilder_.dispose();
          createdAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getCreatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
        if (createdAtBuilder_ != null) {
          return createdAtBuilder_.getMessageOrBuilder();
        } else {
          return createdAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedAtFieldBuilder() {
        if (createdAtBuilder_ == null) {
          createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedAt(),
                  getParentForChildren(),
                  isClean());
          createdAt_ = null;
        }
        return createdAtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nandestech.protos.EventStore)
    }

    // @@protoc_insertion_point(class_scope:nandestech.protos.EventStore)
    private static final nandestech.protos.EventStoreOuterClass.EventStore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new nandestech.protos.EventStoreOuterClass.EventStore();
    }

    public static nandestech.protos.EventStoreOuterClass.EventStore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventStore>
        PARSER = new com.google.protobuf.AbstractParser<EventStore>() {
      @java.lang.Override
      public EventStore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EventStore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventStore> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nandestech.protos.EventStoreOuterClass.EventStore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nandestech_protos_EventStore_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nandestech_protos_EventStore_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+src/main/resources/protos/event_store." +
      "proto\022\021nandestech.protos\032\037google/protobu" +
      "f/timestamp.proto\"\331\001\n\nEventStore\022\026\n\016even" +
      "t_store_id\030\001 \001(\t\022\022\n\nevent_name\030\002 \001(\t\022\023\n\013" +
      "item_number\030\003 \001(\t\022\021\n\titem_type\030\004 \001(\t\022\017\n\007" +
      "user_id\030\005 \001(\005\022\022\n\nuser_login\030\006 \001(\t\022\017\n\007nod" +
      "e_id\030\007 \001(\005\022\021\n\tnode_code\030\010 \001(\t\022.\n\ncreated" +
      "_at\030\t \001(\0132\032.google.protobuf.Timestampb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_nandestech_protos_EventStore_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nandestech_protos_EventStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nandestech_protos_EventStore_descriptor,
        new java.lang.String[] { "EventStoreId", "EventName", "ItemNumber", "ItemType", "UserId", "UserLogin", "NodeId", "NodeCode", "CreatedAt", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
